In [1]:
me="Main hu bhanu pratap"

In [2]:
me.capitalize()

'Main hu bhanu pratap'

In [3]:
me.title()

'Main Hu Bhanu Pratap'

In [4]:
me.lower()

'main hu bhanu pratap'

In [5]:
me.split()

['Main', 'hu', 'bhanu', 'pratap']

In [6]:
line="Tu tu hai mai mai hu vishal"

In [8]:
line.replace(' ','_')

'Tu_tu_hai_mai_mai_hu_vishal'

In [9]:
arr=me.split()

In [10]:
arr

['Main', 'hu', 'bhanu', 'pratap']

In [11]:
arr[-1]

'pratap'

In [12]:
arr[1]

'hu'

In [13]:
arr[1:2]

['hu']

In [14]:
arr[1:3:2]

['hu']

In [16]:
arr[1:-1]

['hu', 'bhanu']

In [17]:
arr

['Main', 'hu', 'bhanu', 'pratap']

In [20]:
del arr[2]

In [21]:
number=[1,2,4,5,3]
number.remove(5)

In [22]:
number

[1, 2, 4, 3]

In [23]:
[1]*2

[1, 1]

In [24]:
[True]*5

[True, True, True, True, True]

In [25]:
str="jkgfkajshlsgnkjhisdfhk"
for i in str:
    print(i)

j
k
g
f
k
a
j
s
h
l
s
g
n
k
j
h
i
s
d
f
h
k


In [26]:
count={}
for c in str:
    if c not in count:
        count[c]=1
    else:
        count[c]+1


In [27]:
count

{'j': 1,
 'k': 1,
 'g': 1,
 'f': 1,
 'a': 1,
 's': 1,
 'h': 1,
 'l': 1,
 'n': 1,
 'i': 1,
 'd': 1}

In [33]:
str="jkgfkajshlsgnkjhisdfhk"
count={}
for c in str:
    count[c]=count.get(c,0)+1
print(count)

{'j': 3, 'k': 4, 'g': 2, 'f': 2, 'a': 1, 's': 3, 'h': 3, 'l': 1, 'n': 1, 'i': 1, 'd': 1}


In [34]:
str=input("Enter any String")
count={}
for i in str:
    count.setdefault(i,0)
    count[i]+=1
print(count)

{'a': 3, 'b': 3, 'c': 3}


In [35]:
number=[1,2,3,4,5,6,7,8,9,10]
print("List[]: {}".format(number))

List[]: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [36]:
import numpy as np

In [37]:
np.array([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
np.array([1,2,3,4,5,6,7,8,9,10],dtype=float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [39]:
np.array([1,2,3,4,5,6,7,8,9,10],dtype=complex)

array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j,
        8.+0.j,  9.+0.j, 10.+0.j])

In [40]:
np.array([1,2,3,4,5,6,7,8,9,10],dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [42]:
np.array([(1,2,3),(4,5,6),(7,8,9)])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
identity_array=np.identity(5)
print(identity_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [48]:
np.eye(5,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [50]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [52]:
np.absolute(-5)

5

In [54]:

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [55]:
np.arange(0,20,2,dtype=float)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [56]:
np.arange(5,2)

array([], dtype=int32)

In [57]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [59]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [60]:
np.random.rand(5)

array([0.44617411, 0.28209121, 0.23591889, 0.67992651, 0.5435274 ])

In [61]:
np.random.rand(5,4)

array([[0.23740474, 0.13508494, 0.01519339, 0.51311441],
       [0.25386037, 0.6569568 , 0.11260681, 0.49711714],
       [0.10828567, 0.94791209, 0.61242635, 0.97464418],
       [0.93157881, 0.27257192, 0.34170453, 0.02569462],
       [0.04808407, 0.37547818, 0.240639  , 0.41778435]])

In [62]:
np.random.randint(1,10)

9

In [63]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

In [64]:
arr[1]

2

In [65]:
arr[2:1]

array([], dtype=int32)

In [66]:
arr=4

In [67]:
arr>5

False

In [68]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0]
[  1   4   9  16  25  36  49  64  81 100]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [69]:
print(np.add(arr1,arr2))

[ 2  4  6  8 10 12 14 16 18 20]


In [70]:
print(np.multiply(arr1,arr2))

[  1   4   9  16  25  36  49  64  81 100]


In [71]:
np.sin(arr)

-0.7568024953079282